spring.application.name=AltasBajasFIEE


spring.datasource.url=jdbc:postgresql://localhost:5432/nexus
spring.datasource.username=nexus_app
spring.datasource.password=${BD_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

